name: Release

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.latest_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: latest_version
        name: Latest version
        run: python version.py >> $GITHUB_OUTPUT

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - versioning
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.versioning.outputs.version }}
          release_name: Release ${{ needs.versioning.outputs.version }}
          draft: false
          prerelease: false

  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - create-release
    strategy:
      matrix:
        os: [linux]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Prepare bin directory
        run: mkdir -p bin
      - name: Generate asset name
        id: gen-asset-name
        run: echo filename=${{ github.event.repository.name }}.${{ matrix.os }}.${{ matrix.arch }}$(python -c "import os; print('.exe' if os.getenv('GOOS') == 'windows' else '', end='')") >> $GITHUB_OUTPUT
      - name: Prepare Git
        run: git config --global url."https://shoriwe:${{ secrets.FINE_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: Generate
        run: go generate ./socrata
      - name: Build binary
        run: go build -tags=jsoniter -v -o bin/${{ steps.gen-asset-name.outputs.filename }} ./cmd/relayer
        env:
          GOEXPERIMENT: jsonv2
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - name: UPX
        run: upx bin/*
      - name: Upload Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./bin/${{ steps.gen-asset-name.outputs.filename }}
          asset_name: ${{ steps.gen-asset-name.outputs.filename }}
          asset_content_type: application/octet-stream
